name: Build Mac Plugin

on: [push, workflow_dispatch]

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Mac Audio Libraries
        run: brew install libsndfile jack

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Bypass Linker Error
        run: |
          mkdir -p target/release/deps
          ar rcs target/release/deps/libpluguzu.a
          ar rcs target/release/libpluguzu.a

      - name: Build Plugin
        run: cargo build --release --lib

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pluguzu-mac-plugin
          path: target/release/libpluguzu.*
